/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    orders: Order;
    'catering-requests': CateringRequest;
    'contact-messages': ContactMessage;
    events: Event;
    'event-bookings': EventBooking;
    'hero-images': HeroImage;
    'newsletter-subscribers': NewsletterSubscriber;
    'site-settings': SiteSetting;
    media: Media;
    recipes: Recipe;
    'cookbook-downloads': CookbookDownload;
    'our-story': OurStory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'catering-requests': CateringRequestsSelect<false> | CateringRequestsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-bookings': EventBookingsSelect<false> | EventBookingsSelect<true>;
    'hero-images': HeroImagesSelect<false> | HeroImagesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    'cookbook-downloads': CookbookDownloadsSelect<false> | CookbookDownloadsSelect<true>;
    'our-story': OurStorySelect<false> | OurStorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description?: string | null;
  price: number;
  /**
   * Upload a photo, or leave empty and use the Image URL field below.
   */
  photo?: (number | null) | Media;
  /**
   * Used only if no photo is uploaded above.
   */
  imageUrl?: string | null;
  stockQuantity?: number | null;
  category?: string | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  isAvailable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  shippingAddress?: string | null;
  billingAddress?: string | null;
  status?: ('pending' | 'confirmed' | 'fulfilled' | 'cancelled') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  paymentMethod?: string | null;
  subtotal: number;
  tax?: number | null;
  shippingCost?: number | null;
  total: number;
  notes?: string | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  items?:
    | {
        productId?: number | null;
        productName: string;
        quantity: number;
        priceAtTime: number;
        subtotal: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-requests".
 */
export interface CateringRequest {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  eventDate?: string | null;
  eventTime?: string | null;
  location?: string | null;
  guestCount?: number | null;
  cateringType?: string | null;
  deliveryType?: string | null;
  eventDetails?: string | null;
  budget?: string | null;
  referral?: string | null;
  selectedMeats?: string | null;
  selectedSides?: string | null;
  selectedDesserts?: string | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  status?: ('new' | 'contacted' | 'confirmed' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  firstName: string;
  lastName?: string | null;
  email: string;
  phoneNumber?: string | null;
  subject?: string | null;
  message: string;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  status?: ('new' | 'read' | 'replied') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: string | null;
  eventDate: string;
  /**
   * One or more time slots guests can choose from (e.g. 6:00 PM, 8:00 PM).
   */
  timeOptions?:
    | {
        time: string;
        availableTickets?: number | null;
        id?: string | null;
      }[]
    | null;
  venue?: string | null;
  ticketPrice?: number | null;
  availableTickets?: number | null;
  /**
   * Upload a photo, or leave empty and use the Image URL field below.
   */
  photo?: (number | null) | Media;
  /**
   * Used only if no photo is uploaded above.
   */
  imageUrl?: string | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-bookings".
 */
export interface EventBooking {
  id: number;
  event: number | Event;
  bookingNumber: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  selectedTime?: string | null;
  quantity: number;
  totalAmount: number;
  paymentMethod?: string | null;
  status?: ('pending' | 'confirmed' | 'cancelled') | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images".
 */
export interface HeroImage {
  id: number;
  /**
   * Upload a photo, or leave empty and use the Image URL field below.
   */
  photo?: (number | null) | Media;
  /**
   * Used only if no photo is uploaded above.
   */
  imageUrl?: string | null;
  title?: string | null;
  subtitle?: string | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  settingKey: string;
  settingValue: string;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  photo?: (number | null) | Media;
  prepTime?: string | null;
  servings?: string | null;
  ingredients?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        step: string;
        id?: string | null;
      }[]
    | null;
  brand?: ('only-pans' | 'pans-and-wine') | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookbook-downloads".
 */
export interface CookbookDownload {
  id: number;
  title: string;
  file: number | Media;
  brand: 'only-pans' | 'pans-and-wine';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story".
 */
export interface OurStory {
  id: number;
  brand: 'only-pans' | 'pans-and-wine';
  body?: string | null;
  /**
   * Upload a photo, or leave empty and use the Image URL field below.
   */
  photo?: (number | null) | Media;
  /**
   * Used only if no photo is uploaded above.
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'catering-requests';
        value: number | CateringRequest;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-bookings';
        value: number | EventBooking;
      } | null)
    | ({
        relationTo: 'hero-images';
        value: number | HeroImage;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'cookbook-downloads';
        value: number | CookbookDownload;
      } | null)
    | ({
        relationTo: 'our-story';
        value: number | OurStory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  photo?: T;
  imageUrl?: T;
  stockQuantity?: T;
  category?: T;
  brand?: T;
  isAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?: T;
  billingAddress?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  subtotal?: T;
  tax?: T;
  shippingCost?: T;
  total?: T;
  notes?: T;
  brand?: T;
  items?:
    | T
    | {
        productId?: T;
        productName?: T;
        quantity?: T;
        priceAtTime?: T;
        subtotal?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-requests_select".
 */
export interface CateringRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  eventDate?: T;
  eventTime?: T;
  location?: T;
  guestCount?: T;
  cateringType?: T;
  deliveryType?: T;
  eventDetails?: T;
  budget?: T;
  referral?: T;
  selectedMeats?: T;
  selectedSides?: T;
  selectedDesserts?: T;
  brand?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phoneNumber?: T;
  subject?: T;
  message?: T;
  brand?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  eventDate?: T;
  timeOptions?:
    | T
    | {
        time?: T;
        availableTickets?: T;
        id?: T;
      };
  venue?: T;
  ticketPrice?: T;
  availableTickets?: T;
  photo?: T;
  imageUrl?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-bookings_select".
 */
export interface EventBookingsSelect<T extends boolean = true> {
  event?: T;
  bookingNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  selectedTime?: T;
  quantity?: T;
  totalAmount?: T;
  paymentMethod?: T;
  status?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images_select".
 */
export interface HeroImagesSelect<T extends boolean = true> {
  photo?: T;
  imageUrl?: T;
  title?: T;
  subtitle?: T;
  displayOrder?: T;
  isActive?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  brand?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  settingKey?: T;
  settingValue?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  photo?: T;
  prepTime?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        item?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  brand?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookbook-downloads_select".
 */
export interface CookbookDownloadsSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story_select".
 */
export interface OurStorySelect<T extends boolean = true> {
  brand?: T;
  body?: T;
  photo?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}